baseurl = "https://www.jakelearnsdatascience.com/"
title = "Jake Learns Data Science"
copyright = "&copy; 2018 Jacob Rozran"
theme = "hugo-coder"
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

[params]
    author = "Jacob Rozran"
    description = "Jacob Rozran's personal website"
    keywords = "blog,developer,personal,data"
    info = "Data Guy, Dad, Uncle, & Friend"
    avatarurl = "images/jakes_pic.jpg"
    footercontent = "It is a capital mistake to theorize before you have all the evidence. - Sherlock Holmes"

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = true

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 1
    url = "https://twitter.com/rozran00/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/jacob-rozran-884580b/"
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 3
    url = "https://github.com/jrozra200/"
[[params.social]]
    name = "WordPress"
    icon = "fab fa-wordpress"
    weight = 4
    url = "https://jakelearnsdatascience.wordpress.com/"
[[params.social]]
    name = "flickr"
    icon = "fab fa-flickr"
    weight = 5
    url = "https://www.flickr.com/photos/jakes_project_365/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"

[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = "Jake Learns Data Science"

        # You can configure the theme parameter for each language.
        [languages.en.params]
        author = "Jacob Rozran"
        info = "Data Guy, Dad, Uncle, & Friend"
        description = "Jacob Rozran's personal website"
        keywords = "blog,developer,personal,data"

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "About"
        weight = 1.0
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2.0
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects/"
        